name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow a manual trigger to publish the build, with a version number as parameter
  workflow_dispatch:
    name: Publish to Maven Central
    inputs:
      version:
        description: 'Version number for the build'
        required: true
      

jobs:
  build_aar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.14.0
        with:
          # The Flutter build release channel
          channel: stable
          # Cache the Flutter SDK
          cache: true
      - name: Run flutter build runner
        run: dart run build_runner build -d
        working-directory: flutter_app

      - name: Run flutter build
        run: flutter build web --wasm --release
        working-directory: flutter_app

      - name: Copy web build to android library
        run: cp -Rv build/web ../android_lib/library/src/androidMain/assets/webapp
        working-directory: flutter_app

      - name: Build android library
        if: github.event_name != 'workflow_dispatch'
        run: ./gradlew :sqlite-web-viewer:assembleRelease
        working-directory: android_lib

      - name: Upload AAR
        if: github.event_name != 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-web-viewer.aar
          path: android_lib/library/build/outputs/aar/sqlite-web-viewer-release.aar

      - name: Publish to Maven Central
        if: github.event_name == 'workflow_dispatch'
        env:
          VERSION: ${{ github.event.inputs.version }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_SIGNING_IN_MEMORY_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: ./gradlew publishToMavenCentral
        working-directory: android_lib
    
     
