name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_aar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.14.0
        with:
          # The Flutter build release channel
          channel: stable
          # Cache the Flutter SDK
          cache: true
      - name: Run flutter build runner
        run: dart run build_runner build -d
        working-directory: flutter_app
      - name: Run flutter build
        run: flutter build web --wasm --release && \
              cp -Rv build/web ../android_lib/library/src/main/assets/webapp
        working-directory: flutter_app
      - name: Build android library
        run: ./gradlew :sqlite-web-viewer:assembleRelease
    
     
